# Generated by Django 4.1.7 on 2023-08-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_task_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.CharField(max_length=200)),
                ('driver', models.CharField(max_length=200)),
                ('date_Created', models.DateField(auto_now=True)),
                ('pickup_loc', models.CharField(max_length=200)),
                ('status_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
